---
- name: "收集 System 健康分数数据"
  aci_rest:
    host:           "{{ aci_host }}"
    user:           "{{ aci_user }}"
    password:       "{{ aci_password }}"
    validate_certs: "{{ aci_valid_cert }}" 
    use_ssl:        "{{ aci_use_ssl }}" 
    path: /api/mo/topology/health.json
    method: get
  register: health_system

- name: "收集 Topology 健康分数数据"
  aci_rest:
    host:           "{{ aci_host }}"
    user:           "{{ aci_user }}"
    password:       "{{ aci_password }}"
    validate_certs: "{{ aci_valid_cert }}" 
    use_ssl:        "{{ aci_use_ssl }}" 
    path: /api/node/class/topSystem.json?rsp-subtree-include=health,required&rsp-subtree-filter=le(healthInst.cur,"{{ item.score }}")
    method: get
  with_items: 
    - score: 100
  register: health_topology

- name: "收集各个 Tenant 的健康分数"
  aci_rest:
    host:           "{{ aci_host }}"
    user:           "{{ aci_user }}"
    password:       "{{ aci_password }}"
    validate_certs: "{{ aci_valid_cert }}" 
    use_ssl:        "{{ aci_use_ssl }}" 
    path: /api/node/class/fvTenant.json?rsp-subtree-include=health,required&rsp-subtree-filter=le(healthInst.cur,"{{ item.score }}")
    method: get
  with_items: 
    - score: 100
  register: health_tenant

- name: "把 System/Topology/Tenant 健康分数存储为 JSON 文件"
  copy:
    content: "{{ item.content | to_nice_json}}"
    dest:    "{{ item.dest }}"
  no_log: yes
  loop:
    - content: "{{ health_system }}"
      dest:    "roles/monitor_health/files/health_system.json"
    - content: "{{ health_topology }}"
      dest:    "roles/monitor_health/files/health_topology.json"
    - content: "{{ health_tenant }}"
      dest:    "roles/monitor_health/files/health_tenant.json"

- name: "执行判断是否要传送消息的脚本（Python）"
  script: check.py
  register: check_result

- name: "把收集的信息以 Webex 接收的文件格式(Markdown)转换"
  template: 
    src:  "template/health_report.j2"
    dest: "roles/call_webex/files/health_report.md"
  when: check_result.stdout | bool
