---
- hosts: all
  remote_user: iacuser

  tasks:
    - name: "메모리 사용량을 확인합니다."
      command: free -m
      register: free

    - name: "이전 task의 실행 결과를 확인합니다."
      debug:
        var: free.stdout_lines
    
    - name: "파일을 읽습니다."
      debug: msg="{{ item }}"
      with_file:
        - '/etc/hosts'
        - '/etc/resolv.conf'
    
    - name: "Nginx 서비스를 실행합니다."
      service: name=nginx state=started
      register: nginx
    
    - name: "Nginx 서비스 실행 결과를 확인합니다."
      debug:
        msg: "{{ nginx.state }}"